# ASSETS
ASSETS = "assets"

# SPRITES
GRASS_SPRITE = f"{ASSETS}/grass.png"
OBSTACLE_SPRITE = f"{ASSETS}/obstacle.png"
BALDUR_ADVENTURE = f"{ASSETS}/TheBaldur_Adventure"
PLAYER_SPRITE_SHEETS = f"{BALDUR_ADVENTURE}/Adventurer/Spritesheets"
PLAYER_IDLE = f"{PLAYER_SPRITE_SHEETS}/Adventurer_Idle.png"
PLAYER_RUN = f"{PLAYER_SPRITE_SHEETS}/Adventurer_Running.png"

# SPRITE CONFIGURATION
PLAYER_IDLE_FRAMES_NUMBER = 5
PLAYER_RUN_FRAMES_NUMBER = 6

# SPRITE DIMENSIONS
PLAYER_RUN_FRAMES_DIMENSIONS = (32, 32)

# DIMENSIONS
GRASS_SIZE = 64
PLAYER_SIZE = 64
OBSTACLE_SIZE = 64

# MISC

PLAYER_JUMP_FORCE = 50
